DROP TABLE IF EXISTS metrics CASCADE;

CREATE TABLE metrics (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         metric_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                         metric_value DOUBLE PRECISION NOT NULL,
                         payload VARCHAR(2000) NOT NULL,
                         client_id VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_metrics_client_id_timestamp
    ON metrics(client_id, metric_timestamp);

